### ISSUE TITLE
Error when sending the command [p]hellohook settings or [p]hellohook test

### ISSUE THREAD

**Issue by fakesmile723** [coffeebank/coffee-cogs#28]
`Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/CogManager/cogs/hellohook/hellohook.py", line 201, in hellohooksettings
    e2.add_field(name="Leave Webhook", value="||"+self.validChecker(guildData.get("leaveWebhook", None))+"||", inline=False)
                                             ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 783, in invoke
    await super().invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1642, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: can only concatenate str (not "NoneType") to str`

**Comment by coffeebank** [comment]
Thanks for the report - Resolved in chat

- New `hellohook` commits https://github.com/coffeebank/coffee-cogs/commit/88c87e4b34557868a66ab324d490484a90ce6049, https://github.com/coffeebank/coffee-cogs/commit/b1ee71ee415cfba9638cbf05f29072225014f2c7 due to Red 3.5 changes
- Updated docs for "How do I send a webhook styled as the person who joined?"
